import { Casa } from "../models/Casa";


export const casasData: Casa[] = [
    {
        id: 1,
        nombre: "Vico Todo en uno",
        precio: 3400000,
        wifi: true,
        parqueadero: true,
        lavanderia: true,
        piscina: true,
        gimnasio: true,
        vigilancia: true,
        numeroHabitaciones: 2,
        EAFIT: true,
        EIA: false,
        UPB: false
    },
    {
        id: 2,
        nombre: "Vico Sweet Jungle",
        precio: 2000000,
        wifi: true,
        parqueadero: true,
        lavanderia: false,
        piscina: false,
        gimnasio: false,
        vigilancia: true,
        numeroHabitaciones: 1,
        EAFIT: true,
        EIA: false,
        UPB: false
    },
    {
        id: 3,
        nombre: "Vico Guadual Habitación 2",
        precio: 1245000,
        wifi: true,
        parqueadero: false,
        lavanderia: true,
        piscina: false,
        gimnasio: false,
        vigilancia: false,
        numeroHabitaciones: 1,
        EAFIT: true,
        EIA: false,
        UPB: false
    },
    {
        id: 4,
        nombre: "Vico Habitación en Patio Bonito",
        precio: 1130000,
        wifi: true,
        parqueadero: true,
        lavanderia: true,
        piscina: false,
        gimnasio: false,
        vigilancia: true,
        numeroHabitaciones: 1,
        EAFIT: true,
        EIA: false,
        UPB: false
    },
    {
        id: 5,
        nombre: "Apartamento en Arriendo, ALTO DE LAS PALMAS",
        precio: 3100000,
        wifi: false,
        parqueadero: true,
        lavanderia: false,
        piscina: false,
        gimnasio: false,
        vigilancia: true,
        numeroHabitaciones: 3,
        EAFIT: false,
        EIA: true,
        UPB: false
    },
    {
        id: 6,
        nombre: "Apartamento en Arriendo, SAN DIEGO LAS PALMAS",
        precio: 3700000,
        wifi: false,
        parqueadero: true,
        lavanderia: false,
        piscina: true,
        gimnasio: true,
        vigilancia: true,
        numeroHabitaciones: 3,
        EAFIT: false,
        EIA: true,
        UPB: false
    },
    {
        id: 7,
        nombre: "Apartamento en Arriendo, LAS PALMAS",
        precio: 3400000,
        wifi: false,
        parqueadero: true,
        lavanderia: false,
        piscina: true,
        gimnasio: true,
        vigilancia: true,
        numeroHabitaciones: 3,
        EAFIT: false,
        EIA: true,
        UPB: false
    },
    {
        id: 8,
        nombre: "Apartamento en Arriendo, LAS PALMAS",
        precio: 2900000,
        wifi: false,
        parqueadero: true,
        lavanderia: true,
        piscina: true,
        gimnasio: true,
        vigilancia: true,
        numeroHabitaciones: 2,
        EAFIT: false,
        EIA: true,
        UPB: false
    },
    {
        id: 9,
        nombre: "APARTAESTUDIO AMOBLADO EN ARRIENDO - CERCA DE LA 70, POR EL ESTADIO",
        precio: 1850000,
        wifi: true,
        parqueadero: false,
        lavanderia: false,
        piscina: false,
        gimnasio: false,
        vigilancia: false,
        numeroHabitaciones: 1,
        EAFIT: false,
        EIA: false,
        UPB: true
    },
    {
        id: 10,
        nombre: "Apartamento cercano a la UPB",
        precio: 2300000,
        wifi: false,
        parqueadero: false,
        lavanderia: false,
        piscina: false,
        gimnasio: false,
        vigilancia: false,
        numeroHabitaciones: 2,
        EAFIT: false,
        EIA: false,
        UPB: true
    },
    {
        id: 11,
        nombre: "Apartamento en Arriendo Ubicado en Medellín Codigo 2707",
        precio: 4000000,
        wifi: false,
        parqueadero: true,
        lavanderia: false,
        piscina: true,
        gimnasio: true,
        vigilancia: true,
        numeroHabitaciones: 3,
        EAFIT: false,
        EIA: false,
        UPB: true
    },
    {
        id: 12,
        nombre: "Apartamento en Arriendo Ubicado en Medellín Codigo 378",
        precio: 2150000,
        wifi: false,
        parqueadero: true,
        lavanderia: false,
        piscina: false,
        gimnasio: false,
        vigilancia: true,
        numeroHabitaciones: 1,
        EAFIT: false,
        EIA: false,
        UPB: true
    }
]